project: {{.projectName}}
service: {{.serviceName}}
ports:
  - port: 9090
    targetPort: 9090
    name: grpc
metrics:
  scrape: true
  port: 5000
  path: /metrics
hpa: false
config:
  - name: {{.projectName}}-{{.serviceName}}-config
    path: /app/cfg